package view;

import controller.DiscotecaController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Marina Savitzki
 */
public class Discoteca extends javax.swing.JFrame {

    private final DiscotecaController controller;

    /**
     * Creates new form Principal
     *
     * @throws java.sql.SQLException
     */
    public Discoteca() throws SQLException {
        initComponents();
        controller = new DiscotecaController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        btnLimparPesquisa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnListaMusica = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        txt_titulo = new javax.swing.JLabel();
        TabelaDiscos = new javax.swing.JScrollPane();
        discos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        anoLancCB = new javax.swing.JComboBox<>();
        artista_bandaCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dadosDiscoPanel = new javax.swing.JPanel();
        idDiscoJTD = new javax.swing.JTextField();
        nomeDiscoJTF = new javax.swing.JTextField();
        artistaBandaJTF = new javax.swing.JTextField();
        anoLancJTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lsitaMusicasCB = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnAddMusica = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMusicasTable = new javax.swing.JTable();
        leftPanel = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimparPesquisa.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnLimparPesquisa.setText("Limpar");
        btnLimparPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnLimparPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Ano de lançamento");
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, -1));

        btnPesquisar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, 30));

        btnListaMusica.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnListaMusica.setText("Ver musicas");
        btnListaMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnListaMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 120, 31));

        btnNovo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnNovo.setText("Novo disco");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 119, 31));

        txt_titulo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("Lista de Discos");
        homePanel.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 740, 26));

        discos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        discos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Disco", "Ano de lançamento", "Artista/Banda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discos.setToolTipText("Selecione uma linha para ver as músicas");
        discos.setAlignmentX(1.0F);
        discos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        discos.setFocusable(false);
        discos.setRowHeight(20);
        discos.setSelectionBackground(new java.awt.Color(102, 153, 255));
        discos.getTableHeader().setReorderingAllowed(false);
        TabelaDiscos.setViewportView(discos);
        if (discos.getColumnModel().getColumnCount() > 0) {
            discos.getColumnModel().getColumn(0).setMinWidth(50);
            discos.getColumnModel().getColumn(0).setPreferredWidth(50);
            discos.getColumnModel().getColumn(0).setMaxWidth(100);
            discos.getColumnModel().getColumn(1).setResizable(false);
            discos.getColumnModel().getColumn(2).setMinWidth(150);
            discos.getColumnModel().getColumn(2).setPreferredWidth(150);
            discos.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        homePanel.add(TabelaDiscos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 740, 460));

        btnExcluir.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 119, 31));

        btnEditar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homePanel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 119, 31));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Fitrar");
        homePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 440, -1));

        anoLancCB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        homePanel.add(anoLancCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, 30));

        artista_bandaCB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        homePanel.add(artista_bandaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Artista/Banda");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, -1));

        centerPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 670));

        dadosDiscoPanel.setBackground(new java.awt.Color(255, 255, 255));

        idDiscoJTD.setEditable(false);

        nomeDiscoJTF.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        artistaBandaJTF.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        artistaBandaJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaBandaJTFActionPerformed(evt);
            }
        });

        anoLancJTF.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Disco");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Artista/Banda");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Ano de lançamento");

        lsitaMusicasCB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Músicas adicionadas ao Disco");

        btnAddMusica.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAddMusica.setText("Adicionar música");
        btnAddMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMusicaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");

        listaMusicasTable.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        listaMusicasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaMusicasTable);
        if (listaMusicasTable.getColumnModel().getColumnCount() > 0) {
            listaMusicasTable.getColumnModel().getColumn(0).setMinWidth(100);
            listaMusicasTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            listaMusicasTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout dadosDiscoPanelLayout = new javax.swing.GroupLayout(dadosDiscoPanel);
        dadosDiscoPanel.setLayout(dadosDiscoPanelLayout);
        dadosDiscoPanelLayout.setHorizontalGroup(
            dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDiscoPanelLayout.createSequentialGroup()
                .addGroup(dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDiscoPanelLayout.createSequentialGroup()
                        .addContainerGap(171, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDiscoPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dadosDiscoPanelLayout.createSequentialGroup()
                                .addGroup(dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lsitaMusicasCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(artistaBandaJTF)
                                    .addComponent(idDiscoJTD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeDiscoJTF)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                    .addComponent(anoLancJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnAddMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dadosDiscoPanelLayout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dadosDiscoPanelLayout.setVerticalGroup(
            dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDiscoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idDiscoJTD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeDiscoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistaBandaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(anoLancJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsitaMusicasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(dadosDiscoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        centerPanel.add(dadosDiscoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 630));

        leftPanel.setBackground(new java.awt.Color(153, 153, 153));

        btn_home.setBackground(new java.awt.Color(204, 204, 204));
        btn_home.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_home.setText("Home");
        btn_home.setBorder(null);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistaBandaJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaBandaJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaBandaJTFActionPerformed

    private void btnAddMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMusicaActionPerformed

    }//GEN-LAST:event_btnAddMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discoteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Discoteca().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Discoteca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelaDiscos;
    private javax.swing.JComboBox<String> anoLancCB;
    private javax.swing.JTextField anoLancJTF;
    private javax.swing.JTextField artistaBandaJTF;
    private javax.swing.JComboBox<String> artista_bandaCB;
    private javax.swing.JButton btnAddMusica;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparPesquisa;
    private javax.swing.JButton btnListaMusica;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btn_home;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel dadosDiscoPanel;
    private javax.swing.JTable discos;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextField idDiscoJTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTable listaMusicasTable;
    private javax.swing.JComboBox<String> lsitaMusicasCB;
    private javax.swing.JTextField nomeDiscoJTF;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JButton getBtnNovo() {
        return btnNovo;
    }

    public void setBtnNovo(JButton btnNovo) {
        this.btnNovo = btnNovo;
    }

    public JButton getBtn_home() {
        return btn_home;
    }

    public void setBtn_home(JButton btn_home) {
        this.btn_home = btn_home;
    }

    public JTable getDiscos() {
        return discos;
    }

    public void setDiscos(JTable discos) {
        this.discos = discos;
    }

    public JPanel getHomePanel() {
        return homePanel;
    }

    public void setHomePanel(JPanel homePanel) {
        this.homePanel = homePanel;
    }

    public JTextField getArtistaBandaJTF() {
        return artistaBandaJTF;
    }

    public void setArtistaBandaJTF(JTextField artistaBandaJTF) {
        this.artistaBandaJTF = artistaBandaJTF;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    public JPanel getDadosDiscoPanel() {
        return dadosDiscoPanel;
    }

    public void setDadosDiscoPanel(JPanel dadosDiscoPanel) {
        this.dadosDiscoPanel = dadosDiscoPanel;
    }

    public JTextField getAnoLancJTF() {
        return anoLancJTF;
    }

    public void setAnoLancJTF(JTextField anoLancJTF) {
        this.anoLancJTF = anoLancJTF;
    }

    public JButton getBtnAddMusica() {
        return btnAddMusica;
    }

    public JTextField getIdDiscoJTD() {
        return idDiscoJTD;
    }

    public void setIdDiscoJTD(JTextField idDiscoJTD) {
        this.idDiscoJTD = idDiscoJTD;
    }
    

    public void setBtnAddMusica(JButton btnAddMusica) {
        this.btnAddMusica = btnAddMusica;
    }

    public JComboBox<String> getLsitaMusicasCB() {
        return lsitaMusicasCB;
    }

    public void setLsitaMusicasCB(JComboBox<String> lsitaMusicasCB) {
        this.lsitaMusicasCB = lsitaMusicasCB;
    }

    public JTextField getNomeDiscoJTF() {
        return nomeDiscoJTF;
    }

    public void setNomeDiscoJTF(JTextField nomeDiscoJTF) {
        this.nomeDiscoJTF = nomeDiscoJTF;
    }


    public JButton getBtnListaMusica() {
        return btnListaMusica;
    }

    public void setBtnListaMusica(JButton btnListaMusica) {
        this.btnListaMusica = btnListaMusica;
    }

    public JComboBox<String> getAnoLancCB() {
        return anoLancCB;
    }

    public void setAnoLancCB(JComboBox<String> anoLancCB) {
        this.anoLancCB = anoLancCB;
    }

    public JComboBox<String> getArtista_bandaCB() {
        return artista_bandaCB;
    }

    public void setArtista_bandaCB(JComboBox<String> artista_bandaCB) {
        this.artista_bandaCB = artista_bandaCB;
    }

    public JButton getBtnPesquisar() {
        return btnPesquisar;
    }

    public void setBtnPesquisar(JButton btnPesquisar) {
        this.btnPesquisar = btnPesquisar;
    }

    public JButton getBtnLimparPesquisa() {
        return btnLimparPesquisa;
    }

    public void setBtnLimparPesquisa(JButton btnLimparPesquisa) {
        this.btnLimparPesquisa = btnLimparPesquisa;
    }

    public JTable getListaMusicasTable() {
        return listaMusicasTable;
    }

    public void setListaMusicasTable(JTable listaMusicasTable) {
        this.listaMusicasTable = listaMusicasTable;
    }

    

}
